AWSTemplateFormatVersion: 2010-09-09
Description: |
  This project converts numbers into Roman numerals.

Resources:
  FatihInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - !Ref FatihInstanceSG
      Tags:
        - Key: Name
          Value: Fatih
        - Key: Project
          Value: Roman-Numerals-Project
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y
          yum install python -y
          yum install pip -y
          pip install Flask
          wget -P templates https://raw.githubusercontent.com/mfaktasit/Roman-Numerals-Converter/main/templates/index.html?token=GHSAT0AAAAAACFPFWTUCWOV3C22DAOLTGYCZIHIOFA
          wget -P templates https://raw.githubusercontent.com/mfaktasit/Roman-Numerals-Converter/main/templates/result.html?token=GHSAT0AAAAAACFPFWTVWT3XKSDOA2HYAB6UZIHIQJQ
          wget https://raw.githubusercontent.com/mfaktasit/Roman-Numerals-Converter/main/roman-numerals-converter-app.py?token=GHSAT0AAAAAACFPFWTVGNWQCB3STWGSOLGGZIHINVQ
          sudo python3 roman-numerals-converter-app.py

  FatihInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH
      GroupName: "Roman-Numerals-ProjectSG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
